// Catálogo de estados de México y sus municipios/alcaldías

export const ESTADOS_MEXICO = [
  'Aguascalientes','Baja California','Baja California Sur','Campeche','Chiapas','Chihuahua','Ciudad de México','Coahuila','Colima','Durango','Estado de México','Guanajuato','Guerrero','Hidalgo','Jalisco','Michoacán','Morelos','Nayarit','Nuevo León','Oaxaca','Puebla','Querétaro','Quintana Roo','San Luis Potosí','Sinaloa','Sonora','Tabasco','Tamaulipas','Tlaxcala','Veracruz','Yucatán','Zacatecas',
];

export const MUNICIPIOS_POR_ESTADO: Record<string, string[]> = {
  'Aguascalientes': ['Aguascalientes','Asientos','Calvillo','Cosío','El Llano','Jesús María','Pabellón de Arteaga','Rincón de Romos','San Francisco de los Romo','San José de Gracia','Tepezalá'],
  'Baja California': ['Ensenada','Mexicali','Playas de Rosarito','Tecate','Tijuana','San Quintín','San Felipe'],
  'Baja California Sur': ['Comondú','La Paz','Loreto','Los Cabos','Mulegé'],
  'Campeche': ['Calakmul','Calkiní','Campeche','Candelaria','Carmen','Champotón','Escárcega','Hecelchakán','Hopelchén','Palizada','Seybaplaya','Tenabo'],
  'Chiapas': ['Berriozábal','Chiapa de Corzo','Comitán de Domínguez','Ocosingo','Palenque','San Cristóbal de las Casas','Tapachula','Tonalá','Tuxtla Gutiérrez','Villaflores'],
  'Chihuahua': ['Aldama','Camargo','Chihuahua','Cuauhtémoc','Delicias','Hidalgo del Parral','Juárez','Meoqui','Nuevo Casas Grandes','Ojinaga'],
  'Ciudad de México': ['Álvaro Obregón','Azcapotzalco','Benito Juárez','Coyoacán','Cuajimalpa de Morelos','Cuauhtémoc','Gustavo A. Madero','Iztacalco','Iztapalapa','La Magdalena Contreras','Miguel Hidalgo','Milpa Alta','Tláhuac','Tlalpan','Venustiano Carranza','Xochimilco'],
  'Coahuila': ['Acuña','Allende','Arteaga','Castaños','Francisco I. Madero','Frontera','General Cepeda','Matamoros','Monclova','Múzquiz','Nava','Parras','Piedras Negras','Ramos Arizpe','Sabinas','Saltillo','San Buenaventura','San Pedro','Torreón','Viesca','Zaragoza'],
  'Colima': ['Armería','Colima','Comala','Coquimatlán','Cuauhtémoc','Ixtlahuacán','Manzanillo','Minatitlán','Tecomán','Villa de Álvarez'],
  'Durango': ['Canatlán','Cuencamé','Durango','El Oro','Gómez Palacio','Guadalupe Victoria','Lerdo','Mapimí','Mezquital','Nombre de Dios','Nuevo Ideal','Pánuco de Coronado','Peñón Blanco','Poanas','Pueblo Nuevo','Santiago Papasquiaro','Tamazula','Tlahualilo','Vicente Guerrero'],
  'Estado de México': ['Atizapán de Zaragoza','Atlacomulco','Chalco','Chimalhuacán','Coacalco','Cuautitlán','Cuautitlán Izcalli','Ecatepec','Huixquilucan','Ixtapaluca','Ixtlahuaca','Jilotepec','Lerma','Metepec','Naucalpan','Nezahualcóyotl','Nicolás Romero','Tecámac','Texcoco','Tlalnepantla','Toluca','Tultitlán','Valle de Chalco','Zinacantepec','Zumpango'],
  'Guanajuato': ['Abasolo','Acámbaro','Celaya','Comonfort','Cortazar','Dolores Hidalgo','Guanajuato','Irapuato','León','Moroleón','Pénjamo','Purísima del Rincón','Salamanca','Salvatierra','San Felipe','San Francisco del Rincón','San Luis de la Paz','San Miguel de Allende','Silao','Uriangato','Valle de Santiago','Yuriria'],
  'Guerrero': ['Acapulco','Chilpancingo','Coyuca de Benítez','Iguala','Taxco','Tlapa','Zihuatanejo'],
  'Hidalgo': ['Actopan','Apan','Huejutla','Ixmiquilpan','Mineral de la Reforma','Pachuca','Tepeapulco','Tepeji del Río','Tizayuca','Tula','Tulancingo'],
  'Jalisco': ['Arandas','Autlán','Chapala','El Salto','Guadalajara','Lagos de Moreno','Ocotlán','Puerto Vallarta','San Juan de los Lagos','Tepatitlán','Tlajomulco','Tlaquepaque','Tonalá','Zapopan'],
  'Michoacán': ['Apatzingán','Hidalgo','La Piedad','Lázaro Cárdenas','Morelia','Pátzcuaro','Sahuayo','Uruapan','Zamora','Zitácuaro'],
  'Morelos': ['Ayala','Cuautla','Cuernavaca','Emiliano Zapata','Jiutepec','Jojutla','Temixco','Xochitepec','Yautepec'],
  'Nayarit': ['Acaponeta','Bahía de Banderas','Compostela','Ixtlán del Río','Santiago Ixcuintla','Tecuala','Tepic','Tuxpan','Xalisco'],
  'Nuevo León': ['Apodaca','Cadereyta','García','General Escobedo','Guadalupe','Juárez','Linares','Monterrey','San Nicolás de los Garza','San Pedro Garza García','Santa Catarina','Santiago'],
  'Oaxaca': ['Huajuapan','Juchitán','Oaxaca de Juárez','Puerto Escondido','Salina Cruz','San Juan Bautista Tuxtepec','Santa Cruz Xoxocotlán','Santa Lucía del Camino','Santo Domingo Tehuantepec'],
  'Puebla': ['Amozoc','Atlixco','Cholula','Huauchinango','Puebla','San Andrés Cholula','San Martín Texmelucan','San Pedro Cholula','Tehuacán','Teziutlán'],
  'Querétaro': ['Corregidora','El Marqués','Querétaro','San Juan del Río'],
  'Quintana Roo': ['Benito Juárez (Cancún)','Cozumel','Felipe Carrillo Puerto','Isla Mujeres','Othón P. Blanco','Playa del Carmen','Tulum'],
  'San Luis Potosí': ['Ciudad Valles','Matehuala','Rioverde','San Luis Potosí','Soledad de Graciano Sánchez','Tamazunchale'],
  'Sinaloa': ['Ahome (Los Mochis)','Culiacán','Guasave','Mazatlán','Navolato','Salvador Alvarado'],
  'Sonora': ['Cajeme (Ciudad Obregón)','Guaymas','Hermosillo','Huatabampo','Navojoa','Nogales','Puerto Peñasco','San Luis Río Colorado'],
  'Tabasco': ['Cárdenas','Centro (Villahermosa)','Comalcalco','Cunduacán','Huimanguillo','Macuspana','Paraíso'],
  'Tamaulipas': ['Altamira','Ciudad Madero','Ciudad Victoria','El Mante','Matamoros','Nuevo Laredo','Reynosa','Río Bravo','Tampico'],
  'Tlaxcala': ['Apizaco','Calpulalpan','Chiautempan','Huamantla','Tlaxcala','Zacatelco'],
  'Veracruz': ['Boca del Río','Coatzacoalcos','Córdoba','Martínez de la Torre','Minatitlán','Orizaba','Poza Rica','Tuxpan','Veracruz','Xalapa'],
  'Yucatán': ['Kanasín','Mérida','Progreso','Tizimín','Umán','Valladolid'],
  'Zacatecas': ['Fresnillo','Guadalupe','Jerez','Loreto','Río Grande','Sombrerete','Zacatecas'],
};

export const SECTORES_ACTIVIDAD = [
  'Agricultura, ganadería, aprovechamiento forestal, pesca y caza',
  'Minería',
  'Electricidad, agua y suministro de gas por ductos al consumidor final',
  'Construcción',
  'Industria manufacturera alimenticia, bebidas o tabaco',
  'Industria manufacturera textil, del vestido y/o accesorios',
  'Industria manufacturera de madera o del papel',
  'Industria manufacturera petroquímica, del carbón, plásticos y hules',
  'Industria manufacturera de metales, maquinaria o transportes',
  'Industria eléctrica, electrónica o de computo',
  'Comercio al por mayor',
  'Comercio al por menor',
  'Transportes, correos y almacenamiento',
  'Información en medios masivos',
  'Servicios financieros y de seguros',
  'Servicios inmobiliarios y de alquiler de bienes muebles e intangibles',
  'Servicios profesionales, científicos y técnicos',
  'Dirección de corporativos y empresas',
  'Servicios de apoyo a negocios, manejo de desechos o remediación',
  'Servicios educativos',
  'Servicios de salud y de asistencia social',
  'Servicios de esparcimiento, culturales y deportivos, y otros servicios',
  'Servicios de alojamiento temporal y de preparación de alimentos y bebidas',
  'Servicios de espectáculo en vivo',
  'Otros servicios excepto actividades del Gobierno',
  'Actividades del Gobierno y de organismos internacionales y extraterritoriales',
  'Servicios personales',
];

export const DOCUMENTOS_PERSONA_FISICA = [
  'Pasaporte',
  'Documento de identidad y viaje',
  'Libreta de mar',
  'Cédula de vecindad',
  'Forma migratoria (con fotografía)',
  'Credencial para votar IFE/INE',
  'Cédula profesional',
  'Certificado de matrícula consular',
  'Carta de naturalización',
  'Cartilla de Servicio Militar Nacional',
  'Documento personal de identidad',
  'Otro',
];
